-- LIVRE sample data. GENERATED by scripts/generate-seed.ts from
-- src/lib/catalog: edit the sample files there, then run
-- npm run db:seed:generate. Safe to run more than once.
begin;

insert into public.materials (key, name_en, name_ar, tone, swatch, sort_order) values
  ('gold', 'Gold Stainless Steel', 'ستانلس ستيل ذهبي', 'gold', '#d9b76e', 0),
  ('silver', 'Silver Stainless Steel', 'ستانلس ستيل فضي', 'silver', '#c9ccd1', 1),
  ('doubleGold', 'Double Gold Stainless Steel', 'ستانلس ستيل بطلاء ذهب مزدوج', 'gold', '#c9a04f', 2),
  ('doubleSilver', 'Double Silver Stainless Steel', 'ستانلس ستيل بطلاء فضة مزدوج', 'silver', '#b4b9c0', 3),
  ('steel', 'Stainless Steel', 'ستانلس ستيل', 'silver', '#9ea3a8', 4)
on conflict (key) do nothing;

insert into public.fonts (key, name_en, name_ar, font_family, script, sort_order) values
  ('beirut', 'Beirut', 'بيروت', 'Great Vibes', 'latin', 0),
  ('byblos', 'Byblos', 'جبيل', 'Allura', 'latin', 1),
  ('batroun', 'Batroun', 'البترون', 'Parisienne', 'latin', 2),
  ('tyre', 'Tyre', 'صور', 'Alex Brush', 'latin', 3),
  ('saida', 'Saida', 'صيدا', 'Pinyon Script', 'latin', 4),
  ('jounieh', 'Jounieh', 'جونية', 'Dancing Script', 'latin', 5),
  ('zahle', 'Zahle', 'زحلة', 'Sacramento', 'latin', 6),
  ('ehden', 'Ehden', 'إهدن', 'Italianno', 'latin', 7),
  ('faraya', 'Faraya', 'فاريا', 'Pacifico', 'latin', 8),
  ('bcharre', 'Bcharre', 'بشري', 'Satisfy', 'latin', 9),
  ('baalbek', 'Baalbek', 'بعلبك', 'Cinzel', 'latin', 10),
  ('anjar', 'Anjar', 'عنجر', 'Playfair Display', 'latin', 11),
  ('tripoli', 'Tripoli', 'طرابلس', 'Aref Ruqaa', 'arabic', 12),
  ('harissa', 'Harissa', 'حريصا', 'Reem Kufi', 'arabic', 13),
  ('deir-el-qamar', 'Deir el Qamar', 'دير القمر', 'Amiri', 'arabic', 14)
on conflict (key) do nothing;

insert into public.categories
  (slug, name_en, name_ar, nav_name_en, nav_name_ar, description_en, description_ar,
   rule, styles, art, art_sample, sort_order) values
  ('name-necklaces', 'Name Necklaces', 'قلادات الأسماء', null, null, 'Your name, their name, a word that means everything. Written in gold or silver stainless steel, made to order and checked by hand before it reaches you.', 'اسمكِ، اسم من تحبين، أو كلمة تعني لكِ الكثير. بالستانلس ستيل الذهبي أو الفضي، تُصنع حسب الطلب وتُفحص يدوياً قبل أن تصلكِ.', null, '{cursive,arabic,bold,dainty,initial,twoFonts}'::text[], '{"kind":"name","variant":"necklace"}'::jsonb, 'Maya', 0),
  ('necklaces', 'Necklaces', 'قلادات', null, null, 'Name necklaces, initials, cedars and coins: everyday pieces made to be layered and loved.', 'قلادات أسماء وأحرف وأرزات وليرات: قطع يومية تُلبس معاً وتدوم.', null, '{}'::text[], '{"kind":"cedar"}'::jsonb, null, 1),
  ('bracelets', 'Bracelets', 'أساور', null, null, 'Delicate name and coin bracelets, sized for your wrist.', 'أساور ناعمة بالأسماء والليرة، على مقاس معصمكِ.', null, '{}'::text[], '{"kind":"name","variant":"bracelet"}'::jsonb, 'Rami', 2),
  ('mens-jewelry', 'Men''s Jewelry', 'مجوهرات رجالية', null, null, 'Bolder chains, cedar and Lira pendants, and Arabic name pieces for him.', 'سلاسل أعرض، أرزة وليرة، وقطع بأسماء عربية له.', null, '{}'::text[], '{"kind":"cedar"}'::jsonb, null, 3),
  ('rings', 'Rings', 'خواتم', null, null, 'Initial signets and dainty stacking rings.', 'خواتم بالأحرف الأولى وخواتم ناعمة تُلبس معاً.', null, '{}'::text[], '{"kind":"ring","engraving":"initial"}'::jsonb, null, 4),
  ('earrings', 'Earrings', 'أقراط', null, null, 'Huggies, pearls and little Lira coins for every day.', 'حلقات صغيرة ولؤلؤ وليرات صغيرة لكل يوم.', null, '{}'::text[], '{"kind":"hoops","pearl":true}'::jsonb, null, 5),
  ('lira-collection', 'Lira Collection', 'مجموعة الليرة', null, null, 'Inspired by the Lebanese coins we grew up with: the 1975 1 Livre, the golden 250 and the silver 500. The cedar on one side, the value on the other. A piece of home to wear every day.', 'مستوحاة من الليرات المعدنية يلي كبرنا معها: ليرة 1975، والـ٢٥٠ الذهبية، والـ٥٠٠ الفضية. الأرزة على وجه والقيمة على الآخر. قطعة من الوطن تلبسينها كل يوم.', null, '{}'::text[], '{"kind":"coin","variant":"necklace"}'::jsonb, null, 6),
  ('gifts', 'Gifts', 'هدايا', null, null, 'Personal gifts they''ll wear every day. Every order comes in our special LIVRE gift box, free.', 'هدايا شخصية تُلبس كل يوم. كل طلبية تصل في علبة هدية خاصة من LIVRE، مجاناً.', null, '{}'::text[], '{"kind":"name","variant":"necklace"}'::jsonb, 'Love', 7),
  ('bestsellers', 'Bestsellers', 'الأكثر مبيعاً', null, null, 'The pieces our customers order again and again.', 'القطع التي تطلبها زبوناتنا مرة بعد مرة.', 'bestsellers', '{}'::text[], '{"kind":"name","variant":"necklace"}'::jsonb, 'Nour', 8),
  ('new', 'New Arrivals', 'وصل حديثاً', 'New', 'جديد', 'Just landed: our newest designs.', 'وصلت للتو: أحدث تصاميمنا.', 'new', '{}'::text[], '{"kind":"hoops","pearl":false}'::jsonb, null, 9)
on conflict (slug) do nothing;

update public.categories c set parent_id = p.id
from (values
  ('name-necklaces', 'necklaces')
) as v (slug, parent_slug)
join public.categories p on p.slug = v.parent_slug
where c.slug = v.slug and c.parent_id is null;

insert into public.products
  (slug, name_en, name_ar, summary_en, summary_ar, description_en, description_ar,
   details_en, details_ar, status, style, is_best_seller, is_new, personalization,
   max_length, sample_text, chain_connections, art, sort_order) values
  ('cursive-name-necklace', 'Cursive Name Necklace', 'قلادة الاسم بخط متصل', 'Your name in flowing handwriting, cut from one piece of metal.', 'اسمكِ بخط يد منساب، مقصوص من قطعة معدن واحدة.', 'Our most loved piece. Type any name or word up to 10 letters and we cut it in one flowing line, then polish it by hand. Wear it alone on a fine chain or layer it with your Lira coin. Every necklace is made to order in Lebanon and arrives in our signature box.', 'القطعة الأحب إلى زبوناتنا. اكتبي أي اسم أو كلمة حتى 10 أحرف ونقصّها بخط واحد منساب ثم نلمّعها يدوياً. البسيها وحدها على سلسلة ناعمة أو مع قلادة الليرة. كل قلادة تُصنع حسب الطلب في لبنان وتصلكِ في علبتنا الخاصة.', 'Pendant height: about 1.5 cm for capital letters, width depends on the name.
Chain: fine cable chain, 1 mm, with a 5 cm extender on 35–45 cm.
Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.', 'ارتفاع الحرف الكبير نحو 1.5 سم، ويختلف العرض حسب الاسم.
السلسلة: سلسلة ناعمة 1 ملم، مع وصلة تطويل 5 سم للمقاسات 35–45 سم.
ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.', 'active', 'cursive', true, false, 'name', 10, 'Maya', '{sides,center}'::public.chain_connection[], '{"kind":"name","variant":"necklace"}'::jsonb, 0),
  ('arabic-name-necklace', 'Arabic Name Necklace', 'قلادة الاسم بالعربي', 'Your name in Arabic calligraphy, joined letter to letter.', 'اسمكِ بالخط العربي، حرفاً موصولاً بحرف.', 'Arabic letters were made to flow. We draw your name in a Ruqaa-inspired script so every letter joins the next, then cut and polish it by hand. A beautiful gift for anyone far from home.', 'الحروف العربية خُلقت لتنساب. نرسم اسمكِ بخط مستوحى من الرقعة فيتصل كل حرف بالذي يليه، ثم نقصّه ونلمّعه يدوياً. هدية جميلة لكل من هو بعيد عن الوطن.', 'Pendant height: about 1.5 cm for capital letters, width depends on the name.
Chain: fine cable chain, 1 mm, with a 5 cm extender on 35–45 cm.
Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.', 'ارتفاع الحرف الكبير نحو 1.5 سم، ويختلف العرض حسب الاسم.
السلسلة: سلسلة ناعمة 1 ملم، مع وصلة تطويل 5 سم للمقاسات 35–45 سم.
ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.', 'active', 'arabic', true, false, 'name', 10, 'ليلى', '{sides,center}'::public.chain_connection[], '{"kind":"name","variant":"necklace"}'::jsonb, 1),
  ('lira-coin-necklace', '1 Livre Coin Necklace', 'قلادة الليرة', 'The 1975 Lebanese Lira, recast as a pendant.', 'ليرة لبنان لعام 1975، بشكل ميدالية.', 'Our signature. The cedar and ''Banque du Liban'' on the front, the laurel wreath and ''1 Livre'' on the back, just like the coin in your teta''s drawer. Wear either side.', 'قطعتنا المميزة. الأرزة و«مصرف لبنان» على الوجه، وإكليل الغار و«١ ليرة» على الظهر، تماماً مثل الليرة في جارور التيتا. البسيها على أي وجه.', 'Coin pendant: 2 cm, both faces of the 1975 1 Livre coin in relief.
Chain: 1.5 mm cable chain.
Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.', 'ميدالية الليرة: 2 سم، بوجهَي ليرة 1975 البارزين.
السلسلة: 1.5 ملم.
ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.', 'active', null, true, false, null, null, null, '{center,sides}'::public.chain_connection[], '{"kind":"coin","variant":"necklace"}'::jsonb, 2),
  ('250-livres-coin-necklace', '250 Livres Coin Necklace', 'قلادة الـ٢٥٠ ليرة', 'The golden 250 of the 90s, with its sunburst of leaves.', 'الـ٢٥٠ الذهبية تبع التسعينات، مع دائرة الأوراق حولها.', 'New in the Lira collection. The 1996 250 Livres was the coin of every manoushe, every bus ride and every "keep the change". We recast it as a pendant with all its details: the cedar and "مصرف لبنان" on one face, the big 250 inside a sunburst of leaves on the other. Wear it alone, or layer it with the 500 for the full story.', 'جديد في مجموعة الليرة. الـ٢٥٠ ليرة تبع ١٩٩٦ كانت ليرة كل منقوشة وكل مشوار بالفان وكل «خلّي الباقي». صببناها ميدالية بكل تفاصيلها: الأرزة و«مصرف لبنان» على وجه، والـ٢٥٠ الكبيرة وسط دائرة أوراق على الوجه الآخر. البسيها وحدها أو مع الـ٥٠٠ لتكتمل القصة.', 'Coin pendant: 2.4 cm, both faces of the 1996 250 Livres coin in relief: the cedar and "مصرف لبنان" on one side, the big 250 on the other.
Chain: 1.5 mm cable chain.
Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.', 'ميدالية الليرة: 2.4 سم، بوجهَي ليرة الـ٢٥٠ 1996 البارزين: الأرزة و«مصرف لبنان» على وجه، والرقم 250 الكبير على الآخر.
السلسلة: 1.5 ملم.
ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.', 'active', null, false, true, null, null, null, '{center,sides}'::public.chain_connection[], '{"kind":"coin","variant":"necklace","coin":250}'::jsonb, 3),
  ('500-livres-coin-necklace', '500 Livres Coin Necklace', 'قلادة الـ٥٠٠ ليرة', 'The silver 500, the biggest coin in your pocket.', 'الـ٥٠٠ الفضية، أكبر ليرة بجيبتك.', 'New in the Lira collection. The 2006 500 Livres, the coin we all saved in a jar. The cedar and "مصرف لبنان" around a bold ٥٠٠ on one face, a strong 500 framed by a ring of panels on the other, recast as a pendant in the metal you choose. A piece of home you can hold, and the perfect gift for anyone who misses it.', 'جديد في مجموعة الليرة. الـ٥٠٠ ليرة تبع ٢٠٠٦، الليرة يلي كلنا جمعناها بالقجّة. الأرزة و«مصرف لبنان» حول ٥٠٠ عريضة على وجه، و500 كبيرة داخل حلقة على الوجه الآخر، مصبوبة ميدالية بالمعدن يلي بتختاريه. قطعة من الوطن بإيدك، وأحلى هدية لكل حدا مشتاقله.', 'Coin pendant: 2.4 cm, both faces of the 2006 500 Livres coin in relief: the cedar and "مصرف لبنان" on one side, the big 500 on the other.
Chain: 1.5 mm cable chain.
Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.', 'ميدالية الليرة: 2.4 سم، بوجهَي ليرة الـ٥٠٠ 2006 البارزين: الأرزة و«مصرف لبنان» على وجه، والرقم 500 الكبير على الآخر.
السلسلة: 1.5 ملم.
ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.', 'active', null, false, true, null, null, null, '{center,sides}'::public.chain_connection[], '{"kind":"coin","variant":"necklace","coin":500}'::jsonb, 4),
  ('name-bracelet', 'Cursive Name Bracelet', 'سوار الاسم بخط متصل', 'A name on your wrist, on a fine chain.', 'اسم على معصمكِ، على سلسلة ناعمة.', 'The same flowing script as our name necklace, sized for the wrist. Adjustable chain, two rings on the sides so the name always sits straight.', 'نفس الخط المنساب لقلادة الاسم، على مقاس المعصم. سلسلة قابلة للتعديل وحلقتان على الجانبين ليبقى الاسم مستقيماً.', 'Pendant height: about 1.5 cm for capital letters, width depends on the name.
Chain: fine cable chain, 1 mm, with a 5 cm extender on 35–45 cm.
Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.', 'ارتفاع الحرف الكبير نحو 1.5 سم، ويختلف العرض حسب الاسم.
السلسلة: سلسلة ناعمة 1 ملم، مع وصلة تطويل 5 سم للمقاسات 35–45 سم.
ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.', 'active', null, true, false, 'name', 10, 'Rami', '{sides,center}'::public.chain_connection[], '{"kind":"name","variant":"bracelet"}'::jsonb, 5),
  ('cedar-necklace', 'Cedar Necklace', 'قلادة الأرزة', 'A little cedar to keep Lebanon close.', 'أرزة صغيرة تبقي لبنان قريباً.', 'A dainty cedar pendant on a fine chain. Our patriotic best seller, and the gift we send most to Lebanese abroad.', 'ميدالية أرزة ناعمة على سلسلة رفيعة. الأكثر مبيعاً من قطعنا الوطنية، والهدية التي نرسلها أكثر للبنانيين في الخارج.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer. Hypoallergenic and nickel free.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج. لا تسبب الحساسية وخالية من النيكل.', 'active', null, true, false, null, null, null, '{center,sides}'::public.chain_connection[], '{"kind":"cedar"}'::jsonb, 6),
  ('initial-necklace', 'Script Initial Necklace', 'قلادة الحرف', 'One letter, big meaning.', 'حرف واحد، ومعنى كبير.', 'Your initial, or the initial of someone you love, in our cursive script. Small enough for every day, easy to layer.', 'حرفكِ الأول أو حرف من تحبين، بخطنا المتصل. صغيرة لكل يوم وسهلة التنسيق مع قلادات أخرى.', 'Pendant height: about 1.5 cm for capital letters, width depends on the name.
Chain: fine cable chain, 1 mm, with a 5 cm extender on 35–45 cm.
Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.', 'ارتفاع الحرف الكبير نحو 1.5 سم، ويختلف العرض حسب الاسم.
السلسلة: سلسلة ناعمة 1 ملم، مع وصلة تطويل 5 سم للمقاسات 35–45 سم.
ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.', 'active', 'initial', true, false, 'initial', 1, 'M', '{center,sides}'::public.chain_connection[], '{"kind":"name","variant":"necklace"}'::jsonb, 7),
  ('bold-name-necklace', 'Bold Name Necklace', 'قلادة الاسم العريضة', 'Thick, rounded letters that stand out.', 'أحرف عريضة ومستديرة تلفت النظر.', 'For the girl who wants her name seen. Rounded, bold script cut thicker than our classic pieces, still light enough to wear all day.', 'لمن تريد أن يُرى اسمها. خط عريض ومستدير أسمك من قطعنا الكلاسيكية، وخفيف بما يكفي لتلبسيه طوال اليوم.', 'Pendant height: about 1.5 cm for capital letters, width depends on the name.
Chain: fine cable chain, 1 mm, with a 5 cm extender on 35–45 cm.
Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.', 'ارتفاع الحرف الكبير نحو 1.5 سم، ويختلف العرض حسب الاسم.
السلسلة: سلسلة ناعمة 1 ملم، مع وصلة تطويل 5 سم للمقاسات 35–45 سم.
ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.', 'active', 'bold', false, true, 'name', 10, 'Jana', '{sides,center}'::public.chain_connection[], '{"kind":"name","variant":"necklace"}'::jsonb, 8),
  ('dainty-name-necklace', 'Dainty Name Necklace', 'قلادة الاسم الناعمة', 'Fine, elegant script for a minimal look.', 'خط رفيع وأنيق لإطلالة بسيطة.', 'Our finest script, with long elegant swirls. Barely-there and perfect for layering with a coin or cedar.', 'أرفع خطوطنا، بانحناءات طويلة وأنيقة. ناعمة جداً ومثالية مع قلادة الليرة أو الأرزة.', 'Pendant height: about 1.5 cm for capital letters, width depends on the name.
Chain: fine cable chain, 1 mm, with a 5 cm extender on 35–45 cm.
Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.', 'ارتفاع الحرف الكبير نحو 1.5 سم، ويختلف العرض حسب الاسم.
السلسلة: سلسلة ناعمة 1 ملم، مع وصلة تطويل 5 سم للمقاسات 35–45 سم.
ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.', 'active', 'dainty', true, false, 'name', 10, 'Rita', '{sides,center}'::public.chain_connection[], '{"kind":"name","variant":"necklace"}'::jsonb, 9),
  ('choose-your-font-name-necklace', 'Choose-Your-Font Name Necklace', 'قلادة الاسم بخط تختارينه', 'Three scripts, one name: pick the one that feels like you.', 'ثلاثة خطوط لاسم واحد: اختاري الذي يشبهكِ.', 'Can''t decide? Preview your name in Beirut, Byblos and Batroun, our three signature scripts, and choose your favorite.', 'محتارة؟ شاهدي اسمكِ بخطوطنا الثلاثة بيروت وجبيل والبترون، واختاري المفضل.', 'Pendant height: about 1.5 cm for capital letters, width depends on the name.
Chain: fine cable chain, 1 mm, with a 5 cm extender on 35–45 cm.
Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.', 'ارتفاع الحرف الكبير نحو 1.5 سم، ويختلف العرض حسب الاسم.
السلسلة: سلسلة ناعمة 1 ملم، مع وصلة تطويل 5 سم للمقاسات 35–45 سم.
ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.', 'active', 'twoFonts', false, true, 'name', 10, 'Sarah', '{sides,center}'::public.chain_connection[], '{"kind":"name","variant":"necklace"}'::jsonb, 10),
  ('arabic-letter-necklace', 'Arabic Letter Necklace', 'قلادة الحرف العربي', 'A single Arabic letter in calligraphy.', 'حرف عربي واحد بخط جميل.', 'One Arabic letter, drawn in calligraphy and cut by hand. Minimal, meaningful and easy to layer.', 'حرف عربي واحد، مرسوم بالخط ومقصوص يدوياً. بسيطة وذات معنى وسهلة التنسيق.', 'Pendant height: about 1.5 cm for capital letters, width depends on the name.
Chain: fine cable chain, 1 mm, with a 5 cm extender on 35–45 cm.
Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.', 'ارتفاع الحرف الكبير نحو 1.5 سم، ويختلف العرض حسب الاسم.
السلسلة: سلسلة ناعمة 1 ملم، مع وصلة تطويل 5 سم للمقاسات 35–45 سم.
ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.', 'active', 'initial', false, true, 'initial', 1, 'ن', '{center,sides}'::public.chain_connection[], '{"kind":"name","variant":"necklace"}'::jsonb, 11),
  ('arabic-name-bracelet', 'Arabic Name Bracelet', 'سوار الاسم بالعربي', 'An Arabic name on a fine chain bracelet.', 'اسم بالعربي على سوار ناعم.', 'Our Arabic calligraphy name, sized for the wrist. Lovely for him or her.', 'اسم بالخط العربي على مقاس المعصم. جميل له أو لها.', 'Pendant height: about 1.5 cm for capital letters, width depends on the name.
Chain: fine cable chain, 1 mm, with a 5 cm extender on 35–45 cm.
Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.', 'ارتفاع الحرف الكبير نحو 1.5 سم، ويختلف العرض حسب الاسم.
السلسلة: سلسلة ناعمة 1 ملم، مع وصلة تطويل 5 سم للمقاسات 35–45 سم.
ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.', 'active', null, false, false, 'name', 10, 'كريم', '{sides,center}'::public.chain_connection[], '{"kind":"name","variant":"bracelet"}'::jsonb, 12),
  ('lira-coin-bracelet', 'Lira Coin Bracelet', 'سوار الليرة', 'A mini Lira coin on a fine chain.', 'ليرة صغيرة على سلسلة ناعمة.', 'The 1 Livre coin in miniature, centered on a delicate bracelet. Pairs perfectly with the coin necklace.', 'ليرة لبنانية مصغّرة في وسط سوار ناعم. تتناسق تماماً مع قلادة الليرة.', 'Coin pendant: 2 cm, both faces of the 1975 1 Livre coin in relief.
Chain: 1.5 mm cable chain.
Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.', 'ميدالية الليرة: 2 سم، بوجهَي ليرة 1975 البارزين.
السلسلة: 1.5 ملم.
ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.', 'active', null, false, false, null, null, null, '{center,sides}'::public.chain_connection[], '{"kind":"coin","variant":"bracelet"}'::jsonb, 13),
  ('lira-coin-earrings', 'Lira Coin Earrings', 'أقراط الليرة', 'Two little Lira coins that catch the light.', 'ليرتان صغيرتان تلمعان مع كل حركة.', 'Tiny 1 Livre coins on fine hooks, cedar side out. Light, playful and very Lebanese.', 'ليرات صغيرة على خطافات رفيعة، والأرزة إلى الخارج. خفيفة ومرحة ولبنانية جداً.', 'Coin pendant: 2 cm, both faces of the 1975 1 Livre coin in relief.
Chain: 1.5 mm cable chain.
Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.', 'ميدالية الليرة: 2 سم، بوجهَي ليرة 1975 البارزين.
السلسلة: 1.5 ملم.
ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.', 'active', null, false, true, null, null, null, '{}'::public.chain_connection[], '{"kind":"coin","variant":"earrings"}'::jsonb, 14),
  ('mens-lira-pendant', 'Men''s Lira Pendant', 'ميدالية الليرة للرجال', 'A larger Lira coin on a stronger chain.', 'ليرة أكبر على سلسلة أمتن.', 'The 1975 Lira at full size on a 2 mm chain. Made to be worn every day.', 'ليرة 1975 بحجمها الكامل على سلسلة 2 ملم. مصنوعة لتُلبس كل يوم.', 'Coin pendant: 2 cm, both faces of the 1975 1 Livre coin in relief.
Chain: 1.5 mm cable chain.
Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.', 'ميدالية الليرة: 2 سم، بوجهَي ليرة 1975 البارزين.
السلسلة: 1.5 ملم.
ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.', 'active', null, false, false, null, null, null, '{center,sides}'::public.chain_connection[], '{"kind":"coin","variant":"necklace"}'::jsonb, 15),
  ('mens-cedar-pendant', 'Men''s Cedar Pendant', 'ميدالية الأرزة للرجال', 'A bold cedar for him.', 'أرزة عريضة له.', 'A larger, heavier cedar on a 2 mm chain. Simple, strong and proudly Lebanese.', 'أرزة أكبر وأثقل على سلسلة 2 ملم. بسيطة وقوية ولبنانية بفخر.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer. Hypoallergenic and nickel free.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج. لا تسبب الحساسية وخالية من النيكل.', 'active', null, false, false, null, null, null, '{center,sides}'::public.chain_connection[], '{"kind":"cedar"}'::jsonb, 16),
  ('initial-signet-ring', 'Initial Signet Ring', 'خاتم الحرف', 'Your initial engraved on a polished signet.', 'حرفكِ محفور على خاتم مصقول.', 'A modern signet with one engraved initial in our cursive script. Stack it or wear it alone.', 'خاتم عصري بحرف واحد محفور بخطنا المتصل. البسيه وحده أو مع خواتم أخرى.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer. Hypoallergenic and nickel free.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج. لا تسبب الحساسية وخالية من النيكل.', 'active', null, false, false, 'initial', 1, 'L', '{}'::public.chain_connection[], '{"kind":"ring","engraving":"initial"}'::jsonb, 17),
  ('dainty-stacking-ring', 'Dainty Stacking Ring', 'خاتم ناعم', 'A thin band to stack and mix.', 'حلقة رفيعة للتنسيق.', 'A 1.2 mm polished band. Wear one, or three in mixed metals.', 'حلقة مصقولة بعرض 1.2 ملم. البسي واحدة أو ثلاثاً بألوان مختلفة.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer. Hypoallergenic and nickel free.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج. لا تسبب الحساسية وخالية من النيكل.', 'active', null, false, true, null, null, null, '{}'::public.chain_connection[], '{"kind":"ring","engraving":"plain"}'::jsonb, 18),
  ('mini-huggie-hoops', 'Mini Huggie Hoops', 'أقراط حلق صغيرة', 'Small hoops that hug the lobe.', 'حلقات صغيرة تلتف حول الأذن.', 'Everyday huggies with a secure click closure. Comfortable enough to sleep in.', 'حلقات يومية بقفل آمن. مريحة لدرجة أنكِ تنامين بها.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer. Hypoallergenic and nickel free.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج. لا تسبب الحساسية وخالية من النيكل.', 'active', null, true, true, null, null, null, '{}'::public.chain_connection[], '{"kind":"hoops","pearl":false}'::jsonb, 19),
  ('pearl-drop-earrings', 'Pearl Drop Earrings', 'أقراط اللؤلؤ', 'A freshwater pearl on a mini hoop.', 'لؤلؤة طبيعية على حلقة صغيرة.', 'A soft freshwater pearl hanging from a mini hoop. Elegant for weddings, easy for every day.', 'لؤلؤة ناعمة معلقة بحلقة صغيرة. أنيقة للأعراس وسهلة لكل يوم.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer. Hypoallergenic and nickel free.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج. لا تسبب الحساسية وخالية من النيكل.', 'active', null, false, false, null, null, null, '{}'::public.chain_connection[], '{"kind":"hoops","pearl":true}'::jsonb, 20),
  ('mens-arabic-name-necklace', 'Men''s Arabic Name Chain', 'سلسلة الاسم بالعربي للرجال', 'A bold Arabic name on a stronger chain.', 'اسم بالعربي بخط عريض على سلسلة أمتن.', 'His name in Arabic calligraphy, cut thicker and hung on a 2 mm chain.', 'اسمه بالخط العربي، مقصوص بسماكة أكبر على سلسلة 2 ملم.', 'Pendant height: about 1.5 cm for capital letters, width depends on the name.
Chain: fine cable chain, 1 mm, with a 5 cm extender on 35–45 cm.
Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.', 'ارتفاع الحرف الكبير نحو 1.5 سم، ويختلف العرض حسب الاسم.
السلسلة: سلسلة ناعمة 1 ملم، مع وصلة تطويل 5 سم للمقاسات 35–45 سم.
ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.', 'active', 'arabic', false, false, 'name', 10, 'علي', '{sides,center}'::public.chain_connection[], '{"kind":"name","variant":"necklace"}'::jsonb, 21)
on conflict (slug) do nothing;

insert into public.product_materials
  (product_id, material_id, price_cents, compare_at_price_cents, is_default, sort_order)
select p.id, m.id, v.price, v.compare_at, v.is_default, v.sort
from (values
  ('cursive-name-necklace', 'silver', 4400, 5800, false, 0),
  ('cursive-name-necklace', 'gold', 4400, 5800, true, 1),
  ('cursive-name-necklace', 'doubleGold', 13200, 17400, false, 3),
  ('arabic-name-necklace', 'silver', 4400, 5700, false, 0),
  ('arabic-name-necklace', 'gold', 4400, 5700, true, 1),
  ('arabic-name-necklace', 'doubleGold', 13200, 17100, false, 3),
  ('lira-coin-necklace', 'silver', 5400, 7000, false, 0),
  ('lira-coin-necklace', 'gold', 5400, 7000, true, 1),
  ('lira-coin-necklace', 'doubleGold', 16200, 21000, false, 2),
  ('250-livres-coin-necklace', 'silver', 5400, 7000, false, 0),
  ('250-livres-coin-necklace', 'gold', 5400, 7000, true, 1),
  ('250-livres-coin-necklace', 'doubleGold', 16200, 21000, false, 3),
  ('500-livres-coin-necklace', 'silver', 5400, 7000, true, 0),
  ('500-livres-coin-necklace', 'gold', 5400, 7000, false, 1),
  ('500-livres-coin-necklace', 'doubleGold', 16200, 21000, false, 3),
  ('name-bracelet', 'silver', 3400, 4400, false, 0),
  ('name-bracelet', 'gold', 3400, 4400, true, 1),
  ('name-bracelet', 'doubleGold', 10200, 13200, false, 3),
  ('cedar-necklace', 'silver', 3400, 4300, false, 0),
  ('cedar-necklace', 'gold', 3400, 4300, true, 1),
  ('cedar-necklace', 'doubleGold', 10200, 12900, false, 3),
  ('initial-necklace', 'silver', 3000, 3700, false, 0),
  ('initial-necklace', 'gold', 3000, 3700, true, 1),
  ('initial-necklace', 'doubleGold', 9000, 11100, false, 3),
  ('bold-name-necklace', 'silver', 4700, 6000, false, 0),
  ('bold-name-necklace', 'gold', 4700, 6000, true, 1),
  ('bold-name-necklace', 'doubleGold', 14100, 18000, false, 3),
  ('dainty-name-necklace', 'silver', 4000, 5000, true, 0),
  ('dainty-name-necklace', 'gold', 4000, 5000, false, 1),
  ('dainty-name-necklace', 'doubleGold', 12000, 15000, false, 3),
  ('choose-your-font-name-necklace', 'silver', 5000, 6400, false, 0),
  ('choose-your-font-name-necklace', 'gold', 5000, 6400, true, 1),
  ('choose-your-font-name-necklace', 'doubleGold', 15000, 19200, false, 3),
  ('arabic-letter-necklace', 'silver', 3000, null::integer, false, 0),
  ('arabic-letter-necklace', 'gold', 3000, null::integer, true, 1),
  ('arabic-letter-necklace', 'doubleGold', 9000, null::integer, false, 3),
  ('arabic-name-bracelet', 'silver', 3700, null::integer, true, 0),
  ('arabic-name-bracelet', 'gold', 3700, null::integer, false, 1),
  ('arabic-name-bracelet', 'doubleGold', 11100, null::integer, false, 3),
  ('lira-coin-bracelet', 'silver', 4000, 5000, false, 0),
  ('lira-coin-bracelet', 'gold', 4000, 5000, true, 1),
  ('lira-coin-bracelet', 'doubleGold', 12000, 15000, false, 2),
  ('lira-coin-earrings', 'silver', 3700, null::integer, false, 0),
  ('lira-coin-earrings', 'gold', 3700, null::integer, true, 1),
  ('lira-coin-earrings', 'doubleGold', 11100, null::integer, false, 2),
  ('mens-lira-pendant', 'silver', 6000, null::integer, true, 0),
  ('mens-lira-pendant', 'gold', 6000, null::integer, false, 1),
  ('mens-lira-pendant', 'doubleGold', 18000, null::integer, false, 2),
  ('mens-cedar-pendant', 'silver', 5000, null::integer, true, 0),
  ('mens-cedar-pendant', 'gold', 5000, null::integer, false, 1),
  ('mens-cedar-pendant', 'doubleGold', 15000, null::integer, false, 2),
  ('initial-signet-ring', 'silver', 4000, 5000, false, 0),
  ('initial-signet-ring', 'gold', 4000, 5000, true, 1),
  ('initial-signet-ring', 'doubleGold', 12000, 15000, false, 3),
  ('dainty-stacking-ring', 'silver', 2400, null::integer, false, 0),
  ('dainty-stacking-ring', 'gold', 2400, null::integer, true, 1),
  ('dainty-stacking-ring', 'doubleGold', 7200, null::integer, false, 3),
  ('mini-huggie-hoops', 'silver', 3000, 3700, false, 0),
  ('mini-huggie-hoops', 'gold', 3000, 3700, true, 1),
  ('mini-huggie-hoops', 'doubleGold', 9000, 11100, false, 3),
  ('pearl-drop-earrings', 'silver', 3700, null::integer, false, 0),
  ('pearl-drop-earrings', 'gold', 3700, null::integer, true, 1),
  ('pearl-drop-earrings', 'doubleGold', 11100, null::integer, false, 3),
  ('mens-arabic-name-necklace', 'silver', 5400, null::integer, true, 0),
  ('mens-arabic-name-necklace', 'gold', 5400, null::integer, false, 1),
  ('mens-arabic-name-necklace', 'doubleGold', 16200, null::integer, false, 2)
) as v (slug, material, price, compare_at, is_default, sort)
join public.products p on p.slug = v.slug
join public.materials m on m.key = v.material
on conflict do nothing;

insert into public.product_options
  (product_id, kind, value, price_modifier_cents, is_default, sort_order)
select p.id, v.kind::public.size_kind, v.value, v.price_modifier, v.is_default, v.sort
from (values
  ('cursive-name-necklace', 'chain', 35, 0, false, 0),
  ('cursive-name-necklace', 'chain', 40, 0, false, 1),
  ('cursive-name-necklace', 'chain', 45, 0, true, 2),
  ('cursive-name-necklace', 'chain', 50, 0, false, 3),
  ('cursive-name-necklace', 'chain', 55, 0, false, 4),
  ('cursive-name-necklace', 'bracelet', 15, -649, false, 100),
  ('cursive-name-necklace', 'bracelet', 16, -649, false, 101),
  ('cursive-name-necklace', 'bracelet', 17, -649, false, 102),
  ('cursive-name-necklace', 'bracelet', 18, -649, false, 103),
  ('cursive-name-necklace', 'bracelet', 19, -649, false, 104),
  ('arabic-name-necklace', 'chain', 35, 0, false, 0),
  ('arabic-name-necklace', 'chain', 40, 0, false, 1),
  ('arabic-name-necklace', 'chain', 45, 0, true, 2),
  ('arabic-name-necklace', 'chain', 50, 0, false, 3),
  ('arabic-name-necklace', 'chain', 55, 0, false, 4),
  ('arabic-name-necklace', 'bracelet', 15, -649, false, 100),
  ('arabic-name-necklace', 'bracelet', 16, -649, false, 101),
  ('arabic-name-necklace', 'bracelet', 17, -649, false, 102),
  ('arabic-name-necklace', 'bracelet', 18, -649, false, 103),
  ('arabic-name-necklace', 'bracelet', 19, -649, false, 104),
  ('lira-coin-necklace', 'chain', 35, 0, false, 0),
  ('lira-coin-necklace', 'chain', 40, 0, false, 1),
  ('lira-coin-necklace', 'chain', 45, 0, true, 2),
  ('lira-coin-necklace', 'chain', 50, 0, false, 3),
  ('lira-coin-necklace', 'chain', 55, 0, false, 4),
  ('lira-coin-necklace', 'bracelet', 15, -649, false, 100),
  ('lira-coin-necklace', 'bracelet', 16, -649, false, 101),
  ('lira-coin-necklace', 'bracelet', 17, -649, false, 102),
  ('lira-coin-necklace', 'bracelet', 18, -649, false, 103),
  ('lira-coin-necklace', 'bracelet', 19, -649, false, 104),
  ('250-livres-coin-necklace', 'chain', 35, 0, false, 0),
  ('250-livres-coin-necklace', 'chain', 40, 0, false, 1),
  ('250-livres-coin-necklace', 'chain', 45, 0, true, 2),
  ('250-livres-coin-necklace', 'chain', 50, 0, false, 3),
  ('250-livres-coin-necklace', 'chain', 55, 0, false, 4),
  ('250-livres-coin-necklace', 'bracelet', 15, -649, false, 100),
  ('250-livres-coin-necklace', 'bracelet', 16, -649, false, 101),
  ('250-livres-coin-necklace', 'bracelet', 17, -649, false, 102),
  ('250-livres-coin-necklace', 'bracelet', 18, -649, false, 103),
  ('250-livres-coin-necklace', 'bracelet', 19, -649, false, 104),
  ('500-livres-coin-necklace', 'chain', 35, 0, false, 0),
  ('500-livres-coin-necklace', 'chain', 40, 0, false, 1),
  ('500-livres-coin-necklace', 'chain', 45, 0, true, 2),
  ('500-livres-coin-necklace', 'chain', 50, 0, false, 3),
  ('500-livres-coin-necklace', 'chain', 55, 0, false, 4),
  ('500-livres-coin-necklace', 'bracelet', 15, -649, false, 100),
  ('500-livres-coin-necklace', 'bracelet', 16, -649, false, 101),
  ('500-livres-coin-necklace', 'bracelet', 17, -649, false, 102),
  ('500-livres-coin-necklace', 'bracelet', 18, -649, false, 103),
  ('500-livres-coin-necklace', 'bracelet', 19, -649, false, 104),
  ('name-bracelet', 'bracelet', 15, 0, false, 0),
  ('name-bracelet', 'bracelet', 16, 0, false, 1),
  ('name-bracelet', 'bracelet', 17, 0, true, 2),
  ('name-bracelet', 'bracelet', 18, 0, false, 3),
  ('name-bracelet', 'bracelet', 19, 0, false, 4),
  ('name-bracelet', 'chain', 35, 649, false, 100),
  ('name-bracelet', 'chain', 40, 649, false, 101),
  ('name-bracelet', 'chain', 45, 649, false, 102),
  ('name-bracelet', 'chain', 50, 649, false, 103),
  ('name-bracelet', 'chain', 55, 649, false, 104),
  ('cedar-necklace', 'chain', 35, 0, false, 0),
  ('cedar-necklace', 'chain', 40, 0, false, 1),
  ('cedar-necklace', 'chain', 45, 0, true, 2),
  ('cedar-necklace', 'chain', 50, 0, false, 3),
  ('cedar-necklace', 'chain', 55, 0, false, 4),
  ('cedar-necklace', 'bracelet', 15, -649, false, 100),
  ('cedar-necklace', 'bracelet', 16, -649, false, 101),
  ('cedar-necklace', 'bracelet', 17, -649, false, 102),
  ('cedar-necklace', 'bracelet', 18, -649, false, 103),
  ('cedar-necklace', 'bracelet', 19, -649, false, 104),
  ('initial-necklace', 'chain', 35, 0, false, 0),
  ('initial-necklace', 'chain', 40, 0, false, 1),
  ('initial-necklace', 'chain', 45, 0, true, 2),
  ('initial-necklace', 'chain', 50, 0, false, 3),
  ('initial-necklace', 'chain', 55, 0, false, 4),
  ('initial-necklace', 'bracelet', 15, -649, false, 100),
  ('initial-necklace', 'bracelet', 16, -649, false, 101),
  ('initial-necklace', 'bracelet', 17, -649, false, 102),
  ('initial-necklace', 'bracelet', 18, -649, false, 103),
  ('initial-necklace', 'bracelet', 19, -649, false, 104),
  ('bold-name-necklace', 'chain', 35, 0, false, 0),
  ('bold-name-necklace', 'chain', 40, 0, false, 1),
  ('bold-name-necklace', 'chain', 45, 0, true, 2),
  ('bold-name-necklace', 'chain', 50, 0, false, 3),
  ('bold-name-necklace', 'chain', 55, 0, false, 4),
  ('bold-name-necklace', 'bracelet', 15, -649, false, 100),
  ('bold-name-necklace', 'bracelet', 16, -649, false, 101),
  ('bold-name-necklace', 'bracelet', 17, -649, false, 102),
  ('bold-name-necklace', 'bracelet', 18, -649, false, 103),
  ('bold-name-necklace', 'bracelet', 19, -649, false, 104),
  ('dainty-name-necklace', 'chain', 35, 0, false, 0),
  ('dainty-name-necklace', 'chain', 40, 0, false, 1),
  ('dainty-name-necklace', 'chain', 45, 0, true, 2),
  ('dainty-name-necklace', 'chain', 50, 0, false, 3),
  ('dainty-name-necklace', 'chain', 55, 0, false, 4),
  ('dainty-name-necklace', 'bracelet', 15, -649, false, 100),
  ('dainty-name-necklace', 'bracelet', 16, -649, false, 101),
  ('dainty-name-necklace', 'bracelet', 17, -649, false, 102),
  ('dainty-name-necklace', 'bracelet', 18, -649, false, 103),
  ('dainty-name-necklace', 'bracelet', 19, -649, false, 104),
  ('choose-your-font-name-necklace', 'chain', 35, 0, false, 0),
  ('choose-your-font-name-necklace', 'chain', 40, 0, false, 1),
  ('choose-your-font-name-necklace', 'chain', 45, 0, true, 2),
  ('choose-your-font-name-necklace', 'chain', 50, 0, false, 3),
  ('choose-your-font-name-necklace', 'chain', 55, 0, false, 4),
  ('choose-your-font-name-necklace', 'bracelet', 15, -649, false, 100),
  ('choose-your-font-name-necklace', 'bracelet', 16, -649, false, 101),
  ('choose-your-font-name-necklace', 'bracelet', 17, -649, false, 102),
  ('choose-your-font-name-necklace', 'bracelet', 18, -649, false, 103),
  ('choose-your-font-name-necklace', 'bracelet', 19, -649, false, 104),
  ('arabic-letter-necklace', 'chain', 35, 0, false, 0),
  ('arabic-letter-necklace', 'chain', 40, 0, false, 1),
  ('arabic-letter-necklace', 'chain', 45, 0, true, 2),
  ('arabic-letter-necklace', 'chain', 50, 0, false, 3),
  ('arabic-letter-necklace', 'chain', 55, 0, false, 4),
  ('arabic-letter-necklace', 'bracelet', 15, -649, false, 100),
  ('arabic-letter-necklace', 'bracelet', 16, -649, false, 101),
  ('arabic-letter-necklace', 'bracelet', 17, -649, false, 102),
  ('arabic-letter-necklace', 'bracelet', 18, -649, false, 103),
  ('arabic-letter-necklace', 'bracelet', 19, -649, false, 104),
  ('arabic-name-bracelet', 'bracelet', 15, 0, false, 0),
  ('arabic-name-bracelet', 'bracelet', 16, 0, false, 1),
  ('arabic-name-bracelet', 'bracelet', 17, 0, true, 2),
  ('arabic-name-bracelet', 'bracelet', 18, 0, false, 3),
  ('arabic-name-bracelet', 'bracelet', 19, 0, false, 4),
  ('arabic-name-bracelet', 'chain', 35, 649, false, 100),
  ('arabic-name-bracelet', 'chain', 40, 649, false, 101),
  ('arabic-name-bracelet', 'chain', 45, 649, false, 102),
  ('arabic-name-bracelet', 'chain', 50, 649, false, 103),
  ('arabic-name-bracelet', 'chain', 55, 649, false, 104),
  ('lira-coin-bracelet', 'bracelet', 15, 0, false, 0),
  ('lira-coin-bracelet', 'bracelet', 16, 0, false, 1),
  ('lira-coin-bracelet', 'bracelet', 17, 0, true, 2),
  ('lira-coin-bracelet', 'bracelet', 18, 0, false, 3),
  ('lira-coin-bracelet', 'bracelet', 19, 0, false, 4),
  ('lira-coin-bracelet', 'chain', 35, 649, false, 100),
  ('lira-coin-bracelet', 'chain', 40, 649, false, 101),
  ('lira-coin-bracelet', 'chain', 45, 649, false, 102),
  ('lira-coin-bracelet', 'chain', 50, 649, false, 103),
  ('lira-coin-bracelet', 'chain', 55, 649, false, 104),
  ('mens-lira-pendant', 'chain', 50, 0, false, 0),
  ('mens-lira-pendant', 'chain', 55, 0, true, 1),
  ('mens-lira-pendant', 'chain', 60, 0, false, 2),
  ('mens-lira-pendant', 'bracelet', 15, -649, false, 100),
  ('mens-lira-pendant', 'bracelet', 16, -649, false, 101),
  ('mens-lira-pendant', 'bracelet', 17, -649, false, 102),
  ('mens-lira-pendant', 'bracelet', 18, -649, false, 103),
  ('mens-lira-pendant', 'bracelet', 19, -649, false, 104),
  ('mens-cedar-pendant', 'chain', 50, 0, false, 0),
  ('mens-cedar-pendant', 'chain', 55, 0, true, 1),
  ('mens-cedar-pendant', 'chain', 60, 0, false, 2),
  ('mens-cedar-pendant', 'bracelet', 15, -649, false, 100),
  ('mens-cedar-pendant', 'bracelet', 16, -649, false, 101),
  ('mens-cedar-pendant', 'bracelet', 17, -649, false, 102),
  ('mens-cedar-pendant', 'bracelet', 18, -649, false, 103),
  ('mens-cedar-pendant', 'bracelet', 19, -649, false, 104),
  ('initial-signet-ring', 'ring', 5, 0, false, 0),
  ('initial-signet-ring', 'ring', 6, 0, false, 1),
  ('initial-signet-ring', 'ring', 7, 0, true, 2),
  ('initial-signet-ring', 'ring', 8, 0, false, 3),
  ('initial-signet-ring', 'ring', 9, 0, false, 4),
  ('dainty-stacking-ring', 'ring', 5, 0, false, 0),
  ('dainty-stacking-ring', 'ring', 6, 0, false, 1),
  ('dainty-stacking-ring', 'ring', 7, 0, true, 2),
  ('dainty-stacking-ring', 'ring', 8, 0, false, 3),
  ('dainty-stacking-ring', 'ring', 9, 0, false, 4),
  ('mens-arabic-name-necklace', 'chain', 50, 0, false, 0),
  ('mens-arabic-name-necklace', 'chain', 55, 0, true, 1),
  ('mens-arabic-name-necklace', 'chain', 60, 0, false, 2),
  ('mens-arabic-name-necklace', 'bracelet', 15, -649, false, 100),
  ('mens-arabic-name-necklace', 'bracelet', 16, -649, false, 101),
  ('mens-arabic-name-necklace', 'bracelet', 17, -649, false, 102),
  ('mens-arabic-name-necklace', 'bracelet', 18, -649, false, 103),
  ('mens-arabic-name-necklace', 'bracelet', 19, -649, false, 104)
) as v (slug, kind, value, price_modifier, is_default, sort)
join public.products p on p.slug = v.slug
on conflict do nothing;

insert into public.product_fonts (product_id, font_id, sort_order)
select p.id, f.id, v.sort
from (values
  ('cursive-name-necklace', 'beirut', 0),
  ('cursive-name-necklace', 'byblos', 1),
  ('cursive-name-necklace', 'batroun', 2),
  ('cursive-name-necklace', 'tyre', 3),
  ('cursive-name-necklace', 'saida', 4),
  ('cursive-name-necklace', 'jounieh', 5),
  ('cursive-name-necklace', 'zahle', 6),
  ('cursive-name-necklace', 'ehden', 7),
  ('cursive-name-necklace', 'faraya', 8),
  ('cursive-name-necklace', 'bcharre', 9),
  ('cursive-name-necklace', 'baalbek', 10),
  ('cursive-name-necklace', 'anjar', 11),
  ('cursive-name-necklace', 'tripoli', 12),
  ('cursive-name-necklace', 'harissa', 13),
  ('cursive-name-necklace', 'deir-el-qamar', 14),
  ('arabic-name-necklace', 'tripoli', 0),
  ('arabic-name-necklace', 'beirut', 1),
  ('arabic-name-necklace', 'byblos', 2),
  ('arabic-name-necklace', 'batroun', 3),
  ('arabic-name-necklace', 'tyre', 4),
  ('arabic-name-necklace', 'saida', 5),
  ('arabic-name-necklace', 'jounieh', 6),
  ('arabic-name-necklace', 'zahle', 7),
  ('arabic-name-necklace', 'ehden', 8),
  ('arabic-name-necklace', 'faraya', 9),
  ('arabic-name-necklace', 'bcharre', 10),
  ('arabic-name-necklace', 'baalbek', 11),
  ('arabic-name-necklace', 'anjar', 12),
  ('arabic-name-necklace', 'harissa', 13),
  ('arabic-name-necklace', 'deir-el-qamar', 14),
  ('name-bracelet', 'beirut', 0),
  ('name-bracelet', 'byblos', 1),
  ('name-bracelet', 'batroun', 2),
  ('name-bracelet', 'tyre', 3),
  ('name-bracelet', 'saida', 4),
  ('name-bracelet', 'jounieh', 5),
  ('name-bracelet', 'zahle', 6),
  ('name-bracelet', 'ehden', 7),
  ('name-bracelet', 'faraya', 8),
  ('name-bracelet', 'bcharre', 9),
  ('name-bracelet', 'baalbek', 10),
  ('name-bracelet', 'anjar', 11),
  ('name-bracelet', 'tripoli', 12),
  ('name-bracelet', 'harissa', 13),
  ('name-bracelet', 'deir-el-qamar', 14),
  ('initial-necklace', 'beirut', 0),
  ('bold-name-necklace', 'faraya', 0),
  ('bold-name-necklace', 'beirut', 1),
  ('bold-name-necklace', 'byblos', 2),
  ('bold-name-necklace', 'batroun', 3),
  ('bold-name-necklace', 'tyre', 4),
  ('bold-name-necklace', 'saida', 5),
  ('bold-name-necklace', 'jounieh', 6),
  ('bold-name-necklace', 'zahle', 7),
  ('bold-name-necklace', 'ehden', 8),
  ('bold-name-necklace', 'bcharre', 9),
  ('bold-name-necklace', 'baalbek', 10),
  ('bold-name-necklace', 'anjar', 11),
  ('bold-name-necklace', 'tripoli', 12),
  ('bold-name-necklace', 'harissa', 13),
  ('bold-name-necklace', 'deir-el-qamar', 14),
  ('dainty-name-necklace', 'beirut', 0),
  ('dainty-name-necklace', 'byblos', 1),
  ('dainty-name-necklace', 'batroun', 2),
  ('dainty-name-necklace', 'tyre', 3),
  ('dainty-name-necklace', 'saida', 4),
  ('dainty-name-necklace', 'jounieh', 5),
  ('dainty-name-necklace', 'zahle', 6),
  ('dainty-name-necklace', 'ehden', 7),
  ('dainty-name-necklace', 'faraya', 8),
  ('dainty-name-necklace', 'bcharre', 9),
  ('dainty-name-necklace', 'baalbek', 10),
  ('dainty-name-necklace', 'anjar', 11),
  ('dainty-name-necklace', 'tripoli', 12),
  ('dainty-name-necklace', 'harissa', 13),
  ('dainty-name-necklace', 'deir-el-qamar', 14),
  ('choose-your-font-name-necklace', 'beirut', 0),
  ('choose-your-font-name-necklace', 'byblos', 1),
  ('choose-your-font-name-necklace', 'batroun', 2),
  ('choose-your-font-name-necklace', 'tyre', 3),
  ('choose-your-font-name-necklace', 'saida', 4),
  ('choose-your-font-name-necklace', 'jounieh', 5),
  ('choose-your-font-name-necklace', 'zahle', 6),
  ('choose-your-font-name-necklace', 'ehden', 7),
  ('choose-your-font-name-necklace', 'faraya', 8),
  ('choose-your-font-name-necklace', 'bcharre', 9),
  ('choose-your-font-name-necklace', 'baalbek', 10),
  ('choose-your-font-name-necklace', 'anjar', 11),
  ('choose-your-font-name-necklace', 'tripoli', 12),
  ('choose-your-font-name-necklace', 'harissa', 13),
  ('choose-your-font-name-necklace', 'deir-el-qamar', 14),
  ('arabic-letter-necklace', 'tripoli', 0),
  ('arabic-letter-necklace', 'harissa', 1),
  ('arabic-letter-necklace', 'deir-el-qamar', 2),
  ('arabic-name-bracelet', 'tripoli', 0),
  ('arabic-name-bracelet', 'beirut', 1),
  ('arabic-name-bracelet', 'byblos', 2),
  ('arabic-name-bracelet', 'batroun', 3),
  ('arabic-name-bracelet', 'tyre', 4),
  ('arabic-name-bracelet', 'saida', 5),
  ('arabic-name-bracelet', 'jounieh', 6),
  ('arabic-name-bracelet', 'zahle', 7),
  ('arabic-name-bracelet', 'ehden', 8),
  ('arabic-name-bracelet', 'faraya', 9),
  ('arabic-name-bracelet', 'bcharre', 10),
  ('arabic-name-bracelet', 'baalbek', 11),
  ('arabic-name-bracelet', 'anjar', 12),
  ('arabic-name-bracelet', 'harissa', 13),
  ('arabic-name-bracelet', 'deir-el-qamar', 14),
  ('initial-signet-ring', 'beirut', 0),
  ('mens-arabic-name-necklace', 'tripoli', 0),
  ('mens-arabic-name-necklace', 'beirut', 1),
  ('mens-arabic-name-necklace', 'byblos', 2),
  ('mens-arabic-name-necklace', 'batroun', 3),
  ('mens-arabic-name-necklace', 'tyre', 4),
  ('mens-arabic-name-necklace', 'saida', 5),
  ('mens-arabic-name-necklace', 'jounieh', 6),
  ('mens-arabic-name-necklace', 'zahle', 7),
  ('mens-arabic-name-necklace', 'ehden', 8),
  ('mens-arabic-name-necklace', 'faraya', 9),
  ('mens-arabic-name-necklace', 'bcharre', 10),
  ('mens-arabic-name-necklace', 'baalbek', 11),
  ('mens-arabic-name-necklace', 'anjar', 12),
  ('mens-arabic-name-necklace', 'harissa', 13),
  ('mens-arabic-name-necklace', 'deir-el-qamar', 14)
) as v (slug, font, sort)
join public.products p on p.slug = v.slug
join public.fonts f on f.key = v.font
on conflict do nothing;

insert into public.product_categories (product_id, category_id, sort_order)
select p.id, c.id, v.sort
from (values
  ('cursive-name-necklace', 'name-necklaces', 0),
  ('cursive-name-necklace', 'necklaces', 1),
  ('cursive-name-necklace', 'gifts', 2),
  ('arabic-name-necklace', 'name-necklaces', 0),
  ('arabic-name-necklace', 'necklaces', 1),
  ('arabic-name-necklace', 'gifts', 2),
  ('lira-coin-necklace', 'lira-collection', 0),
  ('lira-coin-necklace', 'necklaces', 1),
  ('lira-coin-necklace', 'gifts', 2),
  ('250-livres-coin-necklace', 'lira-collection', 0),
  ('250-livres-coin-necklace', 'necklaces', 1),
  ('250-livres-coin-necklace', 'gifts', 2),
  ('500-livres-coin-necklace', 'lira-collection', 0),
  ('500-livres-coin-necklace', 'necklaces', 1),
  ('500-livres-coin-necklace', 'mens-jewelry', 2),
  ('500-livres-coin-necklace', 'gifts', 3),
  ('name-bracelet', 'bracelets', 0),
  ('name-bracelet', 'gifts', 1),
  ('cedar-necklace', 'necklaces', 0),
  ('cedar-necklace', 'gifts', 1),
  ('initial-necklace', 'name-necklaces', 0),
  ('initial-necklace', 'necklaces', 1),
  ('initial-necklace', 'gifts', 2),
  ('bold-name-necklace', 'name-necklaces', 0),
  ('bold-name-necklace', 'necklaces', 1),
  ('dainty-name-necklace', 'name-necklaces', 0),
  ('dainty-name-necklace', 'necklaces', 1),
  ('choose-your-font-name-necklace', 'name-necklaces', 0),
  ('choose-your-font-name-necklace', 'necklaces', 1),
  ('choose-your-font-name-necklace', 'gifts', 2),
  ('arabic-letter-necklace', 'name-necklaces', 0),
  ('arabic-letter-necklace', 'necklaces', 1),
  ('arabic-name-bracelet', 'bracelets', 0),
  ('arabic-name-bracelet', 'mens-jewelry', 1),
  ('lira-coin-bracelet', 'lira-collection', 0),
  ('lira-coin-bracelet', 'bracelets', 1),
  ('lira-coin-bracelet', 'gifts', 2),
  ('lira-coin-earrings', 'lira-collection', 0),
  ('lira-coin-earrings', 'earrings', 1),
  ('mens-lira-pendant', 'lira-collection', 0),
  ('mens-lira-pendant', 'mens-jewelry', 1),
  ('mens-cedar-pendant', 'mens-jewelry', 0),
  ('mens-cedar-pendant', 'necklaces', 1),
  ('initial-signet-ring', 'rings', 0),
  ('initial-signet-ring', 'gifts', 1),
  ('dainty-stacking-ring', 'rings', 0),
  ('mini-huggie-hoops', 'earrings', 0),
  ('mini-huggie-hoops', 'gifts', 1),
  ('pearl-drop-earrings', 'earrings', 0),
  ('pearl-drop-earrings', 'gifts', 1),
  ('mens-arabic-name-necklace', 'mens-jewelry', 0),
  ('mens-arabic-name-necklace', 'name-necklaces', 1)
) as v (slug, category, sort)
join public.products p on p.slug = v.slug
join public.categories c on c.slug = v.category
on conflict do nothing;

insert into public.areas (slug, name_en, name_ar, sort_order) values
  ('beirut', 'Beirut', 'بيروت', 0),
  ('mount-lebanon', 'Mount Lebanon', 'جبل لبنان', 1),
  ('north', 'North', 'الشمال', 2),
  ('south', 'South', 'الجنوب', 3),
  ('bekaa', 'Bekaa', 'البقاع', 4)
on conflict (slug) do nothing;

insert into public.site_settings
  (id, delivery_fee_cents, free_shipping_threshold_cents, first_order_free_delivery,
   whatsapp_number, instagram_url, announcements) values
  (1, 400, 5000, true, '', '', '[{"en":"Design your name necklace","ar":"صمّمي قلادتكِ باسمكِ"},{"en":"Free shipping over $50","ar":"توصيل مجاني للطلبات فوق 50 دولار"},{"en":"Excellent ★★★★★ quality — loved by our customers","ar":"جودة ممتازة ★★★★★ — تحبّها زبوناتنا"}]'::jsonb)
on conflict (id) do nothing;

insert into public.promotions (placement, code, percent, ends_at, sort_order)
select v.placement, v.code, v.percent, v.ends_at::timestamptz, v.sort
from (values
  ('promo_bar', 'STORY15', 15, '2026-10-31T23:59:59+03:00', 0),
  ('hero', null, 25, '2026-10-31T23:59:59+03:00', 1)
) as v (placement, code, percent, ends_at, sort)
where not exists (select 1 from public.promotions);

insert into public.coupons (code, type, value, ends_at) values
  ('STORY15', 'percent', 15, '2026-10-31T23:59:59+03:00')
on conflict (code) do nothing;

insert into public.reviews
  (product_id, customer_name, city, city_ar, rating, text, text_ar, source,
   review_date, is_approved, is_sample)
select p.id, v.name, v.city, v.city_ar, v.rating, v.text, v.text_ar, 'website', v.date::date, true, true
from (values
  ('cursive-name-necklace', 'Maya K.', 'Beirut', 'بيروت', 5, 'Exactly like the preview on the site. The gold is so shiny and it came in the cutest box. My sister already ordered one!', 'تماماً مثل المعاينة على الموقع. الذهب يلمع كثيراً ووصلت في علبة رائعة. أختي طلبت واحدة فوراً!', '2026-09-12'),
  ('lira-coin-necklace', 'Rana H.', 'Jounieh', 'جونية', 5, 'Bought the Lira necklace for my mom, she cried. It really looks like the old coin, both sides.', 'اشتريت قلادة الليرة لأمي وبكت. تشبه الليرة القديمة فعلاً، على الوجهين.', '2026-09-03'),
  ('arabic-name-necklace', 'Lea S.', 'Zahle', 'زحلة', 5, 'The Arabic calligraphy is beautiful and every letter is connected. Delivered in 3 days, paid cash on delivery.', 'الخط العربي جميل وكل الحروف موصولة. وصلت خلال 3 أيام والدفع عند الاستلام.', '2026-08-27'),
  ('cursive-name-necklace', 'Nadine A.', 'Tripoli', 'طرابلس', 5, 'Second order already. The gold one is my favorite, I wear it every day and it still shines.', 'هذا طلبي الثاني. الذهبي المفضل عندي، ألبسه كل يوم وما زال يلمع.', '2026-08-19'),
  ('name-bracelet', 'Joelle M.', 'Byblos', 'جبيل', 4, 'So pretty and delicate. I chose 16 cm and it fits perfectly.', 'ناعم وجميل جداً. اخترت 16 سم وجاء على المقاس تماماً.', '2026-08-08'),
  ('cedar-necklace', 'Sara T.', 'Saida', 'صيدا', 5, 'Sent the cedar necklace to my cousin in Canada. She loved it. The team on WhatsApp was super helpful.', 'أرسلت قلادة الأرزة لبنت خالتي في كندا وأحبّتها كثيراً. الفريق على واتساب كان متعاوناً جداً.', '2026-07-30')
) as v (slug, name, city, city_ar, rating, text, text_ar, date)
left join public.products p on p.slug = v.slug
where not exists (select 1 from public.reviews where is_sample);

commit;
