// Writes supabase/seed.sql from the sample catalog in src/lib/catalog, so
// the database and the static fallback always hold the same data.
//
//   npm run db:seed:generate
//
// The seed is idempotent: running it twice changes nothing (existing rows
// are kept). Prices go in as USD cents; sample reviews as is_sample = true.
import { writeFileSync } from "node:fs";
import { sampleAreas } from "../src/lib/catalog/areas";
import { categories } from "../src/lib/catalog/categories";
import { allFonts, allMaterials, fonts, materials } from "../src/lib/catalog/materials";
import { products } from "../src/lib/catalog/products";
import { reviews } from "../src/lib/catalog/reviews";
import { sampleHeroOffer, samplePromo, sampleSettings } from "../src/lib/catalog/settings";

type Value = string | number | boolean | null | undefined | { raw: string };

const sql = (v: Value): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "object") return v.raw;
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  return `'${v.replace(/'/g, "''")}'`;
};
const raw = (s: string) => ({ raw: s });
const json = (v: unknown) => raw(`${sql(JSON.stringify(v))}::jsonb`);
const textArray = (items: string[], type = "text") =>
  raw(`${sql(`{${items.join(",")}}`)}::${type}[]`);
const cents = (dollars: number | undefined) =>
  dollars === undefined ? null : Math.round(dollars * 100);
const rows = (values: Value[][]) =>
  values.map((r) => `  (${r.map(sql).join(", ")})`).join(",\n");

// Google Fonts behind our font names (see src/components/preview/script-fonts.ts).
const fontFamily: Record<(typeof allFonts)[number], string> = {
  beirut: "Great Vibes",
  byblos: "Allura",
  batroun: "Parisienne",
  tyre: "Alex Brush",
  saida: "Pinyon Script",
  jounieh: "Dancing Script",
  zahle: "Sacramento",
  ehden: "Italianno",
  faraya: "Pacifico",
  bcharre: "Satisfy",
  baalbek: "Cinzel",
  anjar: "Playfair Display",
  tripoli: "Aref Ruqaa",
  harissa: "Reem Kufi",
  "deir-el-qamar": "Amiri",
};


const out: string[] = [];
const add = (s: string) => out.push(s.trim() + "\n");

add(`
-- LIVRE sample data. GENERATED by scripts/generate-seed.ts from
-- src/lib/catalog: edit the sample files there, then run
-- npm run db:seed:generate. Safe to run more than once.
begin;
`);

add(`
insert into public.materials (key, name_en, name_ar, tone, swatch, sort_order) values
${rows(allMaterials.map((k, i) => [k, materials[k].name.en, materials[k].name.ar, materials[k].tone, materials[k].swatch, i]))}
on conflict (key) do nothing;
`);

add(`
insert into public.fonts (key, name_en, name_ar, font_family, script, sort_order) values
${rows(allFonts.map((k, i) => [k, fonts[k].name.en, fonts[k].name.ar, fontFamily[k], fonts[k].script, i]))}
on conflict (key) do nothing;
`);

add(`
insert into public.categories
  (slug, name_en, name_ar, nav_name_en, nav_name_ar, description_en, description_ar,
   rule, styles, art, art_sample, sort_order) values
${rows(
  categories.map((c, i) => [
    c.slug,
    c.name.en,
    c.name.ar,
    c.navName?.en,
    c.navName?.ar,
    c.description.en,
    c.description.ar,
    c.rule,
    textArray(c.styles ?? []),
    json(c.art),
    c.artSample,
    i,
  ]),
)}
on conflict (slug) do nothing;
`);

const parents = categories.filter((c) => c.parent).map((c) => [c.slug, c.parent!]);
if (parents.length > 0) {
  add(`
update public.categories c set parent_id = p.id
from (values
${rows(parents)}
) as v (slug, parent_slug)
join public.categories p on p.slug = v.parent_slug
where c.slug = v.slug and c.parent_id is null;
`);
}

add(`
insert into public.products
  (slug, name_en, name_ar, summary_en, summary_ar, description_en, description_ar,
   details_en, details_ar, status, style, is_best_seller, is_new, personalization,
   max_length, sample_text, chain_connections, art, sort_order) values
${rows(
  products.map((p, i) => [
    p.slug,
    p.name.en,
    p.name.ar,
    p.summary.en,
    p.summary.ar,
    p.description.en,
    p.description.ar,
    p.details.en,
    p.details.ar,
    "active",
    p.style,
    Boolean(p.isBestSeller),
    Boolean(p.isNew),
    p.personalization?.kind,
    p.personalization?.maxLength,
    p.personalization?.sample,
    textArray(p.personalization?.connections ?? [], "public.chain_connection"),
    json(p.art),
    i,
  ]),
)}
on conflict (slug) do nothing;
`);

add(`
insert into public.product_materials
  (product_id, material_id, price_cents, compare_at_price_cents, is_default, sort_order)
select p.id, m.id, v.price, v.compare_at, v.is_default, v.sort
from (values
${rows(
  products.flatMap((p) =>
    p.offers.map((o, i) => [
      p.slug,
      o.material,
      cents(o.price),
      cents(o.compareAtPrice) ?? raw("null::integer"),
      o.material === p.defaultMaterial,
      i,
    ]),
  ),
)}
) as v (slug, material, price, compare_at, is_default, sort)
join public.products p on p.slug = v.slug
join public.materials m on m.key = v.material
on conflict do nothing;
`);

add(`
insert into public.product_options (product_id, kind, value, is_default, sort_order)
select p.id, v.kind::public.size_kind, v.value, v.is_default, v.sort
from (values
${rows(
  products.flatMap((p) =>
    (p.size?.values ?? []).map((value, i) => [
      p.slug,
      p.size!.kind,
      value,
      value === p.size!.default,
      i,
    ]),
  ),
)}
) as v (slug, kind, value, is_default, sort)
join public.products p on p.slug = v.slug
on conflict do nothing;
`);

add(`
insert into public.product_fonts (product_id, font_id, sort_order)
select p.id, f.id, v.sort
from (values
${rows(products.flatMap((p) => (p.personalization?.fonts ?? []).map((font, i) => [p.slug, font, i])))}
) as v (slug, font, sort)
join public.products p on p.slug = v.slug
join public.fonts f on f.key = v.font
on conflict do nothing;
`);

add(`
insert into public.product_categories (product_id, category_id, sort_order)
select p.id, c.id, v.sort
from (values
${rows(products.flatMap((p) => p.categories.map((slug, i) => [p.slug, slug, i])))}
) as v (slug, category, sort)
join public.products p on p.slug = v.slug
join public.categories c on c.slug = v.category
on conflict do nothing;
`);

add(`
insert into public.areas (slug, name_en, name_ar, sort_order) values
${rows(sampleAreas.map((a, i) => [a.slug, a.name.en, a.name.ar, i]))}
on conflict (slug) do nothing;
`);

const s = sampleSettings;
add(`
insert into public.site_settings
  (id, delivery_fee_cents, free_shipping_threshold_cents, first_order_free_delivery,
   whatsapp_number, instagram_url, announcements) values
${rows([[1, cents(s.deliveryFee), cents(s.freeShippingOver), s.firstOrderFreeDelivery, s.whatsappNumber, s.instagramUrl, json(s.announcements)]])}
on conflict (id) do nothing;
`);

add(`
insert into public.promotions (placement, code, percent, ends_at, sort_order)
select v.placement, v.code, v.percent, v.ends_at::timestamptz, v.sort
from (values
${rows([
  ["promo_bar", samplePromo.code, samplePromo.percent, samplePromo.endsAt, 0],
  ["hero", null, sampleHeroOffer.percent, sampleHeroOffer.endsAt, 1],
])}
) as v (placement, code, percent, ends_at, sort)
where not exists (select 1 from public.promotions);
`);

// The promo code must also exist as a coupon so checkout accepts it.
add(`
insert into public.coupons (code, type, value, ends_at) values
${rows([[samplePromo.code, "percent", samplePromo.percent, samplePromo.endsAt]])}
on conflict (code) do nothing;
`);

add(`
insert into public.reviews
  (product_id, customer_name, city, city_ar, rating, text, text_ar, source,
   review_date, is_approved, is_sample)
select p.id, v.name, v.city, v.city_ar, v.rating, v.text, v.text_ar, 'website', v.date::date, true, true
from (values
${rows(reviews.map((r) => [r.productSlug, r.author, r.city.en, r.city.ar, r.rating, r.text.en, r.text.ar, r.date]))}
) as v (slug, name, city, city_ar, rating, text, text_ar, date)
left join public.products p on p.slug = v.slug
where not exists (select 1 from public.reviews where is_sample);
`);

add("commit;");

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n"));
console.log(`supabase/seed.sql written: ${products.length} products, ${categories.length} categories, ${reviews.length} sample reviews.`);
