-- Materials are all stainless steel now: Gold, Silver, Double Gold, Double
-- Silver and plain Stainless Steel. Rose Gold is gone. Every price is typed
-- per product in the admin (price + old price per material).

update public.materials set name_en = 'Gold Stainless Steel', name_ar = 'ستانلس ستيل ذهبي', sort_order = 0
where key = 'gold';
update public.materials set name_en = 'Silver Stainless Steel', name_ar = 'ستانلس ستيل فضي', sort_order = 1
where key = 'silver';
update public.materials set sort_order = 2
where key = 'doubleGold';

insert into public.materials (key, name_en, name_ar, tone, swatch, sort_order) values
  ('doubleSilver', 'Double Silver Stainless Steel', 'ستانلس ستيل بطلاء فضة مزدوج', 'silver', '#b4b9c0', 3),
  ('steel', 'Stainless Steel', 'ستانلس ستيل', 'silver', '#9ea3a8', 4)
on conflict (key) do update set
  name_en = excluded.name_en, name_ar = excluded.name_ar, tone = excluded.tone,
  swatch = excluded.swatch, sort_order = excluded.sort_order, is_active = true;

-- Rose Gold: products stop offering it. The material row stays (inactive) so
-- past orders keep their link; their material_name is saved on the order.
delete from public.product_materials pm
using public.materials m
where m.id = pm.material_id and m.key = 'rose';
update public.materials set is_active = false where key = 'rose';

-- A product that defaulted to Rose Gold falls back to gold, else its first metal.
update public.product_materials pm set is_default = true
from public.materials m
where m.id = pm.material_id and m.key = 'gold'
  and not exists (
    select 1 from public.product_materials d where d.product_id = pm.product_id and d.is_default
  );

update public.product_materials pm set is_default = true
where (pm.product_id, pm.material_id) in (
  select distinct on (x.product_id) x.product_id, x.material_id
  from public.product_materials x
  where not exists (
    select 1 from public.product_materials d where d.product_id = x.product_id and d.is_default
  )
  order by x.product_id, x.sort_order
);

-- Texts: no more Rose Gold or sterling silver 925 in the product, category
-- and sample review texts (only the exact sentences we wrote are replaced;
-- anything the owner rewrote is left alone).
update public.products set
  summary_en = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(summary_en, 'Silver: sterling silver 925. Gold and Rose Gold: sterling silver with a thick gold or rose gold plating. Double Gold Stainless Steel: stainless steel with a double layer of gold, water resistant and made to last.', 'Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.'), 'الفضة: فضة إسترلينية 925. الذهب والذهب الوردي: فضة إسترلينية بطلاء سميك من الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج: ستانلس ستيل بطبقتين من الذهب، مقاوم للماء ويدوم طويلاً.', 'ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.'), 'Stainless steel core with silver, gold or rose gold plating. Double Gold Stainless Steel has a double layer of gold for extra wear. Water resistant.', 'Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.'), 'أساس من الستانلس ستيل مطلي بالفضة أو الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج فيه طبقتان من الذهب لتدوم أكثر. مقاوم للماء.', 'ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.'), 'Sterling silver 925, plain or plated with gold or rose gold, or Double Gold Stainless Steel with a double layer of gold.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer.'), 'فضة إسترلينية 925، طبيعية أو مطلية بالذهب أو الذهب الوردي، أو ستانلس ستيل بطلاء ذهب مزدوج.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج.'), 'Written in gold, silver or rose, made to order', 'Written in gold or silver stainless steel, made to order'), 'بالذهب أو الفضة أو الذهب الوردي، تُصنع', 'بالستانلس ستيل الذهبي أو الفضي، تُصنع'), 'The rose gold is my favorite', 'The gold one is my favorite'), 'الذهب الوردي المفضل عندي', 'الذهبي المفضل عندي'),
  summary_ar = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(summary_ar, 'Silver: sterling silver 925. Gold and Rose Gold: sterling silver with a thick gold or rose gold plating. Double Gold Stainless Steel: stainless steel with a double layer of gold, water resistant and made to last.', 'Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.'), 'الفضة: فضة إسترلينية 925. الذهب والذهب الوردي: فضة إسترلينية بطلاء سميك من الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج: ستانلس ستيل بطبقتين من الذهب، مقاوم للماء ويدوم طويلاً.', 'ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.'), 'Stainless steel core with silver, gold or rose gold plating. Double Gold Stainless Steel has a double layer of gold for extra wear. Water resistant.', 'Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.'), 'أساس من الستانلس ستيل مطلي بالفضة أو الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج فيه طبقتان من الذهب لتدوم أكثر. مقاوم للماء.', 'ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.'), 'Sterling silver 925, plain or plated with gold or rose gold, or Double Gold Stainless Steel with a double layer of gold.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer.'), 'فضة إسترلينية 925، طبيعية أو مطلية بالذهب أو الذهب الوردي، أو ستانلس ستيل بطلاء ذهب مزدوج.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج.'), 'Written in gold, silver or rose, made to order', 'Written in gold or silver stainless steel, made to order'), 'بالذهب أو الفضة أو الذهب الوردي، تُصنع', 'بالستانلس ستيل الذهبي أو الفضي، تُصنع'), 'The rose gold is my favorite', 'The gold one is my favorite'), 'الذهب الوردي المفضل عندي', 'الذهبي المفضل عندي'),
  description_en = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(description_en, 'Silver: sterling silver 925. Gold and Rose Gold: sterling silver with a thick gold or rose gold plating. Double Gold Stainless Steel: stainless steel with a double layer of gold, water resistant and made to last.', 'Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.'), 'الفضة: فضة إسترلينية 925. الذهب والذهب الوردي: فضة إسترلينية بطلاء سميك من الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج: ستانلس ستيل بطبقتين من الذهب، مقاوم للماء ويدوم طويلاً.', 'ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.'), 'Stainless steel core with silver, gold or rose gold plating. Double Gold Stainless Steel has a double layer of gold for extra wear. Water resistant.', 'Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.'), 'أساس من الستانلس ستيل مطلي بالفضة أو الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج فيه طبقتان من الذهب لتدوم أكثر. مقاوم للماء.', 'ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.'), 'Sterling silver 925, plain or plated with gold or rose gold, or Double Gold Stainless Steel with a double layer of gold.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer.'), 'فضة إسترلينية 925، طبيعية أو مطلية بالذهب أو الذهب الوردي، أو ستانلس ستيل بطلاء ذهب مزدوج.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج.'), 'Written in gold, silver or rose, made to order', 'Written in gold or silver stainless steel, made to order'), 'بالذهب أو الفضة أو الذهب الوردي، تُصنع', 'بالستانلس ستيل الذهبي أو الفضي، تُصنع'), 'The rose gold is my favorite', 'The gold one is my favorite'), 'الذهب الوردي المفضل عندي', 'الذهبي المفضل عندي'),
  description_ar = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(description_ar, 'Silver: sterling silver 925. Gold and Rose Gold: sterling silver with a thick gold or rose gold plating. Double Gold Stainless Steel: stainless steel with a double layer of gold, water resistant and made to last.', 'Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.'), 'الفضة: فضة إسترلينية 925. الذهب والذهب الوردي: فضة إسترلينية بطلاء سميك من الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج: ستانلس ستيل بطبقتين من الذهب، مقاوم للماء ويدوم طويلاً.', 'ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.'), 'Stainless steel core with silver, gold or rose gold plating. Double Gold Stainless Steel has a double layer of gold for extra wear. Water resistant.', 'Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.'), 'أساس من الستانلس ستيل مطلي بالفضة أو الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج فيه طبقتان من الذهب لتدوم أكثر. مقاوم للماء.', 'ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.'), 'Sterling silver 925, plain or plated with gold or rose gold, or Double Gold Stainless Steel with a double layer of gold.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer.'), 'فضة إسترلينية 925، طبيعية أو مطلية بالذهب أو الذهب الوردي، أو ستانلس ستيل بطلاء ذهب مزدوج.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج.'), 'Written in gold, silver or rose, made to order', 'Written in gold or silver stainless steel, made to order'), 'بالذهب أو الفضة أو الذهب الوردي، تُصنع', 'بالستانلس ستيل الذهبي أو الفضي، تُصنع'), 'The rose gold is my favorite', 'The gold one is my favorite'), 'الذهب الوردي المفضل عندي', 'الذهبي المفضل عندي'),
  details_en = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(details_en, 'Silver: sterling silver 925. Gold and Rose Gold: sterling silver with a thick gold or rose gold plating. Double Gold Stainless Steel: stainless steel with a double layer of gold, water resistant and made to last.', 'Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.'), 'الفضة: فضة إسترلينية 925. الذهب والذهب الوردي: فضة إسترلينية بطلاء سميك من الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج: ستانلس ستيل بطبقتين من الذهب، مقاوم للماء ويدوم طويلاً.', 'ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.'), 'Stainless steel core with silver, gold or rose gold plating. Double Gold Stainless Steel has a double layer of gold for extra wear. Water resistant.', 'Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.'), 'أساس من الستانلس ستيل مطلي بالفضة أو الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج فيه طبقتان من الذهب لتدوم أكثر. مقاوم للماء.', 'ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.'), 'Sterling silver 925, plain or plated with gold or rose gold, or Double Gold Stainless Steel with a double layer of gold.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer.'), 'فضة إسترلينية 925، طبيعية أو مطلية بالذهب أو الذهب الوردي، أو ستانلس ستيل بطلاء ذهب مزدوج.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج.'), 'Written in gold, silver or rose, made to order', 'Written in gold or silver stainless steel, made to order'), 'بالذهب أو الفضة أو الذهب الوردي، تُصنع', 'بالستانلس ستيل الذهبي أو الفضي، تُصنع'), 'The rose gold is my favorite', 'The gold one is my favorite'), 'الذهب الوردي المفضل عندي', 'الذهبي المفضل عندي'),
  details_ar = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(details_ar, 'Silver: sterling silver 925. Gold and Rose Gold: sterling silver with a thick gold or rose gold plating. Double Gold Stainless Steel: stainless steel with a double layer of gold, water resistant and made to last.', 'Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.'), 'الفضة: فضة إسترلينية 925. الذهب والذهب الوردي: فضة إسترلينية بطلاء سميك من الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج: ستانلس ستيل بطبقتين من الذهب، مقاوم للماء ويدوم طويلاً.', 'ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.'), 'Stainless steel core with silver, gold or rose gold plating. Double Gold Stainless Steel has a double layer of gold for extra wear. Water resistant.', 'Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.'), 'أساس من الستانلس ستيل مطلي بالفضة أو الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج فيه طبقتان من الذهب لتدوم أكثر. مقاوم للماء.', 'ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.'), 'Sterling silver 925, plain or plated with gold or rose gold, or Double Gold Stainless Steel with a double layer of gold.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer.'), 'فضة إسترلينية 925، طبيعية أو مطلية بالذهب أو الذهب الوردي، أو ستانلس ستيل بطلاء ذهب مزدوج.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج.'), 'Written in gold, silver or rose, made to order', 'Written in gold or silver stainless steel, made to order'), 'بالذهب أو الفضة أو الذهب الوردي، تُصنع', 'بالستانلس ستيل الذهبي أو الفضي، تُصنع'), 'The rose gold is my favorite', 'The gold one is my favorite'), 'الذهب الوردي المفضل عندي', 'الذهبي المفضل عندي')
where summary_en ~* '(rose|925|وردي|إسترلين|استرلين)' or summary_ar ~* '(rose|925|وردي|إسترلين|استرلين)' or description_en ~* '(rose|925|وردي|إسترلين|استرلين)' or description_ar ~* '(rose|925|وردي|إسترلين|استرلين)' or details_en ~* '(rose|925|وردي|إسترلين|استرلين)' or details_ar ~* '(rose|925|وردي|إسترلين|استرلين)';
update public.categories set
  description_en = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(description_en, 'Silver: sterling silver 925. Gold and Rose Gold: sterling silver with a thick gold or rose gold plating. Double Gold Stainless Steel: stainless steel with a double layer of gold, water resistant and made to last.', 'Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.'), 'الفضة: فضة إسترلينية 925. الذهب والذهب الوردي: فضة إسترلينية بطلاء سميك من الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج: ستانلس ستيل بطبقتين من الذهب، مقاوم للماء ويدوم طويلاً.', 'ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.'), 'Stainless steel core with silver, gold or rose gold plating. Double Gold Stainless Steel has a double layer of gold for extra wear. Water resistant.', 'Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.'), 'أساس من الستانلس ستيل مطلي بالفضة أو الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج فيه طبقتان من الذهب لتدوم أكثر. مقاوم للماء.', 'ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.'), 'Sterling silver 925, plain or plated with gold or rose gold, or Double Gold Stainless Steel with a double layer of gold.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer.'), 'فضة إسترلينية 925، طبيعية أو مطلية بالذهب أو الذهب الوردي، أو ستانلس ستيل بطلاء ذهب مزدوج.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج.'), 'Written in gold, silver or rose, made to order', 'Written in gold or silver stainless steel, made to order'), 'بالذهب أو الفضة أو الذهب الوردي، تُصنع', 'بالستانلس ستيل الذهبي أو الفضي، تُصنع'), 'The rose gold is my favorite', 'The gold one is my favorite'), 'الذهب الوردي المفضل عندي', 'الذهبي المفضل عندي'),
  description_ar = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(description_ar, 'Silver: sterling silver 925. Gold and Rose Gold: sterling silver with a thick gold or rose gold plating. Double Gold Stainless Steel: stainless steel with a double layer of gold, water resistant and made to last.', 'Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.'), 'الفضة: فضة إسترلينية 925. الذهب والذهب الوردي: فضة إسترلينية بطلاء سميك من الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج: ستانلس ستيل بطبقتين من الذهب، مقاوم للماء ويدوم طويلاً.', 'ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.'), 'Stainless steel core with silver, gold or rose gold plating. Double Gold Stainless Steel has a double layer of gold for extra wear. Water resistant.', 'Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.'), 'أساس من الستانلس ستيل مطلي بالفضة أو الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج فيه طبقتان من الذهب لتدوم أكثر. مقاوم للماء.', 'ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.'), 'Sterling silver 925, plain or plated with gold or rose gold, or Double Gold Stainless Steel with a double layer of gold.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer.'), 'فضة إسترلينية 925، طبيعية أو مطلية بالذهب أو الذهب الوردي، أو ستانلس ستيل بطلاء ذهب مزدوج.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج.'), 'Written in gold, silver or rose, made to order', 'Written in gold or silver stainless steel, made to order'), 'بالذهب أو الفضة أو الذهب الوردي، تُصنع', 'بالستانلس ستيل الذهبي أو الفضي، تُصنع'), 'The rose gold is my favorite', 'The gold one is my favorite'), 'الذهب الوردي المفضل عندي', 'الذهبي المفضل عندي')
where description_en ~* '(rose|925|وردي|إسترلين|استرلين)' or description_ar ~* '(rose|925|وردي|إسترلين|استرلين)';
update public.reviews set
  text = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(text, 'Silver: sterling silver 925. Gold and Rose Gold: sterling silver with a thick gold or rose gold plating. Double Gold Stainless Steel: stainless steel with a double layer of gold, water resistant and made to last.', 'Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.'), 'الفضة: فضة إسترلينية 925. الذهب والذهب الوردي: فضة إسترلينية بطلاء سميك من الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج: ستانلس ستيل بطبقتين من الذهب، مقاوم للماء ويدوم طويلاً.', 'ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.'), 'Stainless steel core with silver, gold or rose gold plating. Double Gold Stainless Steel has a double layer of gold for extra wear. Water resistant.', 'Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.'), 'أساس من الستانلس ستيل مطلي بالفضة أو الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج فيه طبقتان من الذهب لتدوم أكثر. مقاوم للماء.', 'ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.'), 'Sterling silver 925, plain or plated with gold or rose gold, or Double Gold Stainless Steel with a double layer of gold.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer.'), 'فضة إسترلينية 925، طبيعية أو مطلية بالذهب أو الذهب الوردي، أو ستانلس ستيل بطلاء ذهب مزدوج.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج.'), 'Written in gold, silver or rose, made to order', 'Written in gold or silver stainless steel, made to order'), 'بالذهب أو الفضة أو الذهب الوردي، تُصنع', 'بالستانلس ستيل الذهبي أو الفضي، تُصنع'), 'The rose gold is my favorite', 'The gold one is my favorite'), 'الذهب الوردي المفضل عندي', 'الذهبي المفضل عندي'),
  text_ar = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(text_ar, 'Silver: sterling silver 925. Gold and Rose Gold: sterling silver with a thick gold or rose gold plating. Double Gold Stainless Steel: stainless steel with a double layer of gold, water resistant and made to last.', 'Gold, Silver and plain Stainless Steel: water resistant and made to last. Double Gold and Double Silver Stainless Steel: a double layer of plating for extra wear.'), 'الفضة: فضة إسترلينية 925. الذهب والذهب الوردي: فضة إسترلينية بطلاء سميك من الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج: ستانلس ستيل بطبقتين من الذهب، مقاوم للماء ويدوم طويلاً.', 'ستانلس ستيل ذهبي أو فضي أو عادي: مقاوم للماء ويدوم طويلاً. ستانلس ستيل بطلاء ذهب أو فضة مزدوج: طبقتان من الطلاء لتدوم أكثر.'), 'Stainless steel core with silver, gold or rose gold plating. Double Gold Stainless Steel has a double layer of gold for extra wear. Water resistant.', 'Stainless steel in gold, silver or plain steel. Double Gold and Double Silver Stainless Steel have a double layer for extra wear. Water resistant.'), 'أساس من الستانلس ستيل مطلي بالفضة أو الذهب أو الذهب الوردي. ستانلس ستيل بطلاء ذهب مزدوج فيه طبقتان من الذهب لتدوم أكثر. مقاوم للماء.', 'ستانلس ستيل ذهبي أو فضي أو عادي. الستانلس بطلاء الذهب أو الفضة المزدوج فيه طبقتان لتدوم أكثر. مقاوم للماء.'), 'Sterling silver 925, plain or plated with gold or rose gold, or Double Gold Stainless Steel with a double layer of gold.', 'Stainless steel in gold, silver or plain steel, or Double Gold / Double Silver Stainless Steel with a double layer.'), 'فضة إسترلينية 925، طبيعية أو مطلية بالذهب أو الذهب الوردي، أو ستانلس ستيل بطلاء ذهب مزدوج.', 'ستانلس ستيل ذهبي أو فضي أو عادي، أو بطلاء ذهب أو فضة مزدوج.'), 'Written in gold, silver or rose, made to order', 'Written in gold or silver stainless steel, made to order'), 'بالذهب أو الفضة أو الذهب الوردي، تُصنع', 'بالستانلس ستيل الذهبي أو الفضي، تُصنع'), 'The rose gold is my favorite', 'The gold one is my favorite'), 'الذهب الوردي المفضل عندي', 'الذهبي المفضل عندي')
where text ~* '(rose|925|وردي|إسترلين|استرلين)' or text_ar ~* '(rose|925|وردي|إسترلين|استرلين)';
